#!/usr/bin/env bash
# installs nginx listening at port 80
# when sent a GET request at it's root, sends the response "Holberton School"
apt-get -y install nginx
echo "Holberton School for the win!" | cat > /usr/share/nginx/html/index.html
srvice nginx restart
