#! /usr/bin/env bash
# manages start, stop and restart command arguments for the
# manage_my_process file

STATUS=$(pgrep -f ./manage_my_process)

do_start () {
    ./manage_my_process &
    pgrep -f ./manage_my_process
}

do_stop () {
    pkill -f ./manage_my_process;
}

do_restart () {
    do_stop
    do_start
}

case "$1" in
    start)
	# echo $$ # (un)comment to show/hide PID when beginning process
	if [ "$STATUS" != "" ]; then
	    echo "PID $STATUS already running";
	    exit
	fi
	do_start
	echo "manage_my_process started"
	# ;; # maybe remove ;;'s
    stop)
	if [ "$STATUS" == "" ]; then
	    echo "manage_my_process already stopped"
	    exit
	fi
	do_stop
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	# ;;
    restart)
	if [ "$STATUS" == ""  ]; then
	    echo "manage_my_process not running"
	    exit
	fi
	do_restart
	echo manage_my_process restarted
	# ;;
    *)
	echo 'Usage: manage_my_process {start|stop|restart}'
	# ;;
esac
