#!/usr/bin/env bash
# loops from 1 to 10 w. "bad luck on 4", "good luck" on and
# "Holbert School" for the others
i=0; while [ $i -lt 10 ]; do if [[ "$i" == 3 ]]; then echo "good luck";
elif [[ $i == 7 ]]; then echo "bad luck"; else echo "Holbertson School"; fi;
let i+=1; done
