#!/usr/bin/env bash
# outputs 1 to 20 with case conditions depending on iteration
#case EXPRESSION in CASE1) COMMAND-LIST;; CASE2) COMMAND-LIST;; ... CASEN) COMMAND-LIST;; esac
i=1;
while [ $i -le 20 ]; do
    echo $i
    case $i in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
	
	    esac;
    let i+=1;
done
