#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
i=0;
j=1;
while [ $i -le 12 ]
do
    echo Hour: $i;
    while [ $j -lt 60 ]
    do
	echo $j;
	let j+=1;
    done;
    j=1
    let i+=1;
done
