#!/usr/bin/env bash
# installs nginx and adds the a custom header
shellcheck -e SC2154 myscript
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "21i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
